### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by terrorist96**

### CODE REVIEW

**Comment by KacperZajc** [comment]
I've changed this bit on the oath of secrecy and now I cannot merge your PR.

**Comment by terrorist96** [comment]
Would you prefer your version or should I make another PR with my wording (all parties vs all Persons)?

**Comment by KacperZajc** [comment]
I actually wanted to use 'all Parties' but then I realised that the term 'parties' traditionally refers only to prosecution/defence, not anyone adjudicating the dispute or working in the administration of the court.

**Comment by terrorist96** [comment]
Really? I would think that 'all parties' would include anyone and everyone
who is involved (i.e. the Judge, the prosecutor and his team, the defense
and their team, the jury, a bailiff, a court stenographer, etc.)

**Comment by KacperZajc** [comment]
Probably depends who you ask but this is not how I would construe this term so it is safer to use 'persons'.

**Pull request closed without merging**
