### PR TITLE
Moving the Bill of Rights ahead, renumbering its paragraphs by article.

### PR DESCRIPTION
**Pull request by fare**
Including article number in every paragraph number.
*NOT* modifying the contents of any paragraph.

This pull request corresponds to #29.

Also, fixed some whitespace, and added a heading "Political Institutions" for the section that follows the "Bill of Rights".

### CODE REVIEW

**Comment by KacperZajc** [comment]
#30 modifications?

**Comment by fare** [comment]
This is independent from #30, but since renumbering changes every line, it's better done sooner than later.

**Comment by KacperZajc** [comment]
let's modify and then renumber

**Comment by fare** [comment]
I might even recommend moving individual rights first, and move the "general provisions" to the end of the bill of rights.

**Comment by KacperZajc** [comment]
no problem but no point renumbering without necessary modifications

**Comment by fare** [comment]
Well, please push modifications for #30, and I'll merge modifications since 3c27aceb0acf2b21241f21aed15a9b1e01548c28 into my branch.

**Comment by fare** [comment]
I'd rather the renumbering happen separately from any modification, so it's easy to trace that I did not in fact modify anything while I renumber.

**Comment by KacperZajc** [comment]
I just want people to consent to the modifications I listed, then we can renumber, no point doing it twice

**Comment by rotilho** [comment]
+fare
Renumbering and #30 are different issues

**Comment by burningtree** [comment]
Note: KacperZajc does not have much experience with Git.

Git (and GitHub) works on the principle of evolution, where you can comment on any changes. Changes in documents should happen transparently in steps. This intention should be preserved.

**Comment by KacperZajc** [comment]
that is true, I have no experience with Git
if you prefer go ahead and renumber first
I only insist on modifications to move our discussion forward

**Comment by fare** [comment]
I don't have write access to the main repository (and do not request to have it at this time). Someone who has it shall accept my pull request.

**Comment by burningtree** [comment]
@KacperZajc I'll leave it on you. I just wanted to point out that it would be unfortunate if further changes came in one commit like changes from draft1 => draft2
https://github.com/liberland/constitution/commit/70dc673e64cfe8056f1be4270986a7055b7c03ff

You can edit document right here on GitHub - https://github.com/liberland/constitution/edit/master/Liberland-constitution.md
or in Pull request you can apply changes just by clicking on "Merge pull request"

**Pull request merged**
