### PR TITLE
Non-Individual Rights

### PR DESCRIPTION
**Pull request by yopdog**
I believe it's important we have a provision in the constitution that protects the rights of non-individuals as well. Children should have the right to be protected from their Guardians and the Guardians should have the right to decide what's right for their children. 

>§II.40. No law shall allow for Non-Individuals to be subjected to any form of treatment without the expressed approval of their Guardian otherwise pursuant to a Warrant and under exigent circumstances where the Guardian is refusing to allow for essential medical treatment; nor shall it allow Non-Individuals to be subjected to any permanent and/or harmful treatment which is not medically necessary by their Guardians or anybody else.

P.S. We need a better word for "Non-Individuals"

### CODE REVIEW

**Comment by terrorist96** [comment]
Minors, since non-individual would include criminals and the mentally insane.

**Comment by yopdog** [comment]
Why are criminals considered Non-Individuals? Isn't being an Individual what makes them responsible for their actions? 

As for the use of the word 'Minors', it doesn't cover persons who lack mental capacity. This provision should cover any person who isn't capable of making his own decision due to age or mental reasons. It should therefore cover 'mentally insane' as well.

**Comment by terrorist96** [comment]
Individuals have a right to bear arms, for example. Criminals do not.

**Comment by terrorist96** [comment]
Individual” shall signify a Person of age who does not lack mental capacity and is not incarcerated following a conviction in a court of law

**Comment by yopdog** [comment]
>§II.40. No law shall allow for **Minors and those who lack mental capacity** to be subjected to any form of treatment without the expressed approval of their Guardian otherwise pursuant to a Warrant and under exigent circumstances where the Guardian is refusing to allow for essential medical treatment; nor shall it allow **Minors and those who lack mental capacity** to be subjected to any permanent and/or harmful treatment which is not medically necessary by their Guardians or anybody else.

??

**Comment by terrorist96** [comment]
What if the mentally ill person doesn't have a guardian?

**Comment by Auahi** [comment]
I don't like this one part "where the Guardian is refusing to allow for essential medical treatment" 

I could easily see government using this as a way to have compulsory vaccination for minors even though the guardian objects...

**Comment by Auahi** [comment]
@terrorist96 I'm assuming it would be the state then

**Comment by yopdog** [comment]
Yes, it will probably be up to the courts to decide what's best for the person in that case.

**Comment by Auahi** [comment]
also isn't most of this covered throughout the constitution

I like this part:
  * **§II.40.** No law shall allow for Non-Individuals to be subjected to any form of treatment without the expressed approval of their Guardian

the other parts are mentioned throughout the constitution, torture and harmful punishment are already outlawed - I think

**Comment by yopdog** [comment]
@Auahi We have to find a balance between the control society has on minors and the control parents have over their children. Parents don't completely own their children since their children are humans who have rights just like anybody else. The court's should therefore be able to interfere in extreme cases inorder to protect the child. I think my suggestion balances this out well, leaning slightly more towards the parent's side.

**Comment by Auahi** [comment]
@yopdog Yes I agree, but any medical treatment can be deemed essential depending on who you ask. Maybe if it said something like this

§II.40. No law shall allow for Non-Individuals to be subjected to any form of treatment without the expressed approval of their Guardian; nor shall it allow Non-Individuals to be subjected to any permanent and/or harmful treatment which is not medically necessary by their Guardians or anybody else. 
§II.40(1) An emergency Warrant may be issued for Non-Individuals only in cases where death is imminent if no medical treatment occurs

**Comment by yopdog** [comment]
What if the child isn't going to die, but is in danger of being permanently crippled if he doesn't receive treatment?

**Comment by yopdog** [comment]
I think what I wrote is sufficient. I made it very clear that treatment of a child without the parent's consent can only be done in extreme cases, and only with a warrant. 

>otherwise pursuant to a **Warrant** and under **exigent circumstances** where the Guardian is refusing to allow for **essential** medical treatment

**Comment by Auahi** [comment]
I just really don't want vaccination policies like that of Malaysia and Slovenia. I think it's a basic Human right to deny something so unnatural like vaccines. I don't want to get into a vaccine debate here so lets just say I'm supporting non compulsory vaccines. 

But anyways "exigent circumstances" this is interpreted by the reader, and same goes for essential.

Someone could argue that you'll be crippled if you don't get the MMR shot, but others say you won't

Another example would be parents who'd rather you natural and herbal medicine rather than use Big pharma. The government could get a warrant to force certain treatments.

Now I do understand for when this bill could be used, like for example there are religions who'd rather refuse all medical treatments including refusing blood transfusions, and I see how it could be used there but unfortunately this bill will easily be abused for other purposes

**Comment by Auahi** [comment]
Oh and I'm not saying your pull is bad, I see the good in it, I just feel it could easily be abused

**Comment by yopdog** [comment]
Since vaccination isn't 'essential medical treatment' It will be illegal under this provision to have compulsory vaccination. 

As for your concern that this can be abused, yes it can be abused and it can be interpreted in thousands of different ways, this is just how the law works. Law isn't programming, there is always going to be the possibility of misinterpretation and abuse. Our job is to do the best we can in order prevent this. 
    
Concerning this provision, I still believe having this provision is better then nothing. If we don't allow for the court's to interfere in exigent circumstances then we have the problem of parents who can harm their children because of idiotic/religious reasons.

**Comment by KacperZajc** [comment]
I agree that we need more protection for vulnerable persons, here is my wording: 

§II.40. No law shall allow for Minors and those who lack mental capacity to be subjected to any form of treatment without the expressed approval of their Guardian unless under exigent circumstances where no rejection or consent can be obtained; Guardian's decision shall be capable of being overridden by an order of the Civil Court where the doctors are able to prove that the decision in question is not in the best interest of the patient.

**Comment by KacperZajc** [comment]
I agree that we need more protection for vulnerable persons, here is my wording:

§II.40. No law shall allow for Minors and those who lack mental capacity to be subjected to any form of treatment without either express approval of their Guardian or with their own consent where appropriate unless under exigent circumstances where no rejection or consent can be obtained; Guardian's decision shall be capable of being overridden by an order of the Civil Court where the doctors are able to prove that the decision in question is not in the best interest of the patient.

**Comment by Auahi** [comment]
@kacperZajc i dislike this version even more, I know i said i did not like what yopdog put into there but know i feel the way he wrote it is a little more "leanent" as in it can only be done in emergency situations

What you wrote will essentially give parents no write whatsoever to question doctors! For example most doctors do not think of natural medication as  adequate, so doctors could force children to take other medications. Amd same can go for things like ADHD and different minor "autistic" disorders  and have children forcefully put onto these medications. These are things im striving for in the world to not have a place where parents have no say in what goes into childrens bodys. In the united states doctors try to manipulate parents into doing everything they say, where in most cases doctors arent 100%  knowledgeable about all subjects. For example many doctors tell parents that don't want their child to be vaccinated or only partly vaccinated that they need all vaccinations to survive ehich is clearly not true! 

Putting something like this into the constitution allows for doctors to do whats in the best intreset of their pockets as well, all doctors here profit very much off of cancer treatments( they make  Commission  off of chemotherapy) and there have been many studies showing that doctors are over giving out these treatments by a lot. Now lets say a parent researches this and they dont want chemotherapy since its a drug for profit and decide to go to a natural route for their child, in liberland with this law they can force the child to take chemo

This is not right at all. I understand how yopdog put it and its more for emergency cases but with what you wrote makes it so that any time a parent questions a doctor and refuses things where death or being severly crippled isnt going to be an outcome of the child, the doctor could just say that this ir that is in the best interest of the child. And we have seen that doctors are never always right! 

Im sorry but that law allows for doctors to have complete control over children 

I say a 100% Nay

**Comment by KacperZajc** [comment]
Doctors cannot force parents to do anything. They can apply to court to override their decision. We must have a safeguard so that children wont die because of their parents' ridiculous religious beliefs etc.

**Comment by Auahi** [comment]
Yes okay im agreeing with that! Im just saying how your worded the last sentence it makes it so everything the doctor deems as in the best interest they can go to court over and easily win because they're the doctors amd most people think that just because youre a doctor youre automatically right which i could see happen in many court cases...

I just dont want doctors to have 100% contol, some is neccesary but never 100%

**Comment by KacperZajc** [comment]
it clearly says that doctors have to prove that parents' decision is not in the child's best interest, it is not easy and certainly not 100% :)

**Comment by yopdog** [comment]
@KacperZajc I'm leaning more towards Auahi's side on this. Your suggestion is slightly more lenient in it's wording then mine. I don't think we should omit the "essential medical treatment" condition from the provision since it makes it less clear as to when it's ok to interfere with a parents decision. Secondly, you took out the second part that is supposed to protect the Minors from their own Guardian who might want to subject them to a harmful treatment. 

I still stand on my suggestion, but with a small addition in the end which will allow minors to undergo non-medically necessary treatment in special cases (e.g., sex change, plastic surgery) where there is agreement from both the minor and the parent.  

>§II.40. No law shall allow for Minors and those who lack mental capacity to be subjected to any form of treatment without the expressed approval of their Guardian otherwise pursuant to a Warrant and under exigent circumstances where the Guardian is refusing to allow for essential medical treatment; nor shall it allow Minors and those who lack mental capacity to be subjected to any permanent and/or harmful treatment which is not medically necessary by their Guardians or anybody else, otherwise in special cases where both the Minor/Mentally Challenged Person and the Guardian agree to the treatment.

**Comment by KacperZajc** [comment]
now?

§II.40. No law shall allow for Minors and those who lack mental capacity to be subjected to any form of treatment without either express approval of their Guardian or with their own consent where appropriate unless under exigent circumstances where no rejection or consent can be obtained; Guardian's decision shall be capable of being overridden by an order of the Civil Court where the doctors are able to prove that the decision in question is not in the best interest of the patient and the treatment is essential for the life of the patient; nor shall it allow Minors and those who lack mental capacity to be subjected to any permanent and/or harmful treatment which is not medically necessary by their Guardians or anybody else, otherwise in special cases where both the Minor and those lacking capacity and their Guardian agree to the treatment.

**Comment by yopdog** [comment]
Yes this is good.

**Comment by terrorist96** [comment]
This subject is running into II.21 "no Individual shall be subjected to any medical treatment without one's express and informed consent absent exigent circumstances where an Individual is incapable of consenting or refusing."

That last part of II.21 should be merged with this new provision in order to keep the subject matter cohesive instead of spreading it amongst different provisions.

**Comment by KacperZajc** [comment]
§II.40. No law shall allow for any Individual to be subjected to any medical treatment without one's express and informed consent absent exigent circumstances where an Individual is incapable of consenting or refusing; nor shall any Minors or those who lack mental capacity to be subjected to any form of treatment without either express approval of their Guardian or with their own consent where appropriate unless under exigent circumstances where no rejection or consent can be obtained; Guardian's decision shall be capable of being overridden by an order of the Civil Court where the doctors are able to prove that the decision in question is not in the best interest of the patient and the treatment is essential for the life of the patient; nor shall it allow Minors and those who lack mental capacity to be subjected to any permanent and/or harmful treatment which is not medically necessary by their Guardians or anybody else, otherwise in special cases where both the Minor and those lacking capacity and their Guardian agree to the treatment.

§II.21. No law shall allow for the application of torture or other cruel, unusual, or degrading treatment against any Person against their will and informed consent, nor shall any experiments be done in such manner.

**Comment by Auahi** [comment]
@KacperZajc I like this version

**Pull request closed without merging**
