### PR TITLE
clean up of arms amendment

### PR DESCRIPTION
**Pull request by terrorist96**
removed extraneous period, reworded warrant clause

### CODE REVIEW

**Comment by Jean-LouisMesic** [comment]
Can we revise the syntax of the final clause, as well?

"no property owner shall be denied the right to disallow the carrying of arms by any person within the bounds of his or her premises, except in the case of an agent of the Public Administration pursuant of a warrant issued by a court of the Free Republic of Liberland that is relevant specifically to the premises and/or its owner, residents, and/or patrons."

**Comment by terrorist96** [comment]
> no property owner shall be denied the right to disallow the carrying of arms by any person within the bounds of his or her premises, except in the case of an agent of the Public Administration **acting** pursuant **to** a warrant issued by a court of the Free Republic of Liberland that is relevant specifically to the premises and/or its owner, residents, and/or patrons.

This has my approval.

**Comment by Jean-LouisMesic** [comment]
@terrorist96 +1 to your further revision.

**Comment by terrorist96** [comment]
Made one more edit.

**Comment by terrorist96** [comment]
I will let @KacperZajc decide if he wants this merged.

**Comment by Jean-LouisMesic** [comment]
@terrorist96 "issued by a...Liberland" is just parallel syntax with the rest of the document, and is necessary. Because, by this logic, what about a warrant issued directly by the Public Administration? Clearly, it should be heinously illegal, but isn't, because we didn't stipulate who could issue the warrant allowing this action.

**Comment by terrorist96** [comment]
Which is why it should be defined in the dedicated section.

**Comment by KacperZajc** [comment]
I will clean up all 'warrant' provisions once we introduce a separate section on warrants :)

**Comment by Jean-LouisMesic** [comment]
+1

**Pull request closed without merging**
