### PR TITLE
Removed superfluous language

### PR DESCRIPTION
**Pull request by terrorist96**
This wording covers any number of law enforcement members.

### CODE REVIEW

**Comment by Jean-LouisMesic** [comment]
From a constitutional context, "law enforcement" does not refer to any agency, nor any number of agents. It represents a concept, not a body. This is not superfluous language, it is part of constitutional syntax.

**Comment by terrorist96** [comment]
That's the beauty of it. It covers testimony by any number of law enforcement agents and regardless of their department.

**Comment by Jean-LouisMesic** [comment]
A concept cannot give testimony. "Law enforcement" alone is a.) not an institution as the Constitution currently stands, and b.) the idea of acting upon legislation. The idea of acting upon legislation cannot provide testimony in a court case.

This is a flaw presented even in the original wording. It should be "any number of agents of the law enforcing body of the Public Administration" to maintain parallel syntax with the rest of the document.

**Comment by terrorist96** [comment]
I'll let you win this one. :smile:

**Comment by Jean-LouisMesic** [comment]
@terrorist96 I hope I don't seem so condescending in these threads, xD I'm enjoying having someone to debate with with such vigor.

**Comment by terrorist96** [comment]
Likewise :)

**Pull request closed without merging**
