### PR TITLE
Pursuit vs pursuance

### PR DESCRIPTION
**Pull request by terrorist96**

### CODE REVIEW

**Comment by terrorist96** [comment]
Google says that "in pursuance of a warrant" is a more common phrase than "in pursuit of a warrant".
The former means you're acting in accordance to a warrant, the latter means you are attempting to procure a warrant. I think that all instances of this phrase should be changed to the former. Thoughts?

**Comment by KacperZajc** [comment]
or pursuant to ?

**Comment by terrorist96** [comment]
"Pursuant to" and "in pursuance of" have the same meaning, just different phrasing. I'm ok with either.

**Comment by KacperZajc** [comment]
I will change it everywhere to "in pursuance of" :)

**Comment by KacperZajc** [comment]
I will change it everywhere to "pursuant to" then :)

**Comment by terrorist96** [comment]
Cool. :smile:

**Comment by terrorist96** [comment]
> otherwise than in pursuit of a Warrant

would become

> otherwise pursuant to a Warrant

or

> otherwise than in pursuance of a Warrant.

Also, the capitalization of Warrant should be standardized.

**Comment by KacperZajc** [comment]
otherwise than pursuant to a Warrant?

**Comment by terrorist96** [comment]
"Than" is unnecessary in that case. At least from my understanding. We need some English majors in here. :laughing:

**Comment by terrorist96** [comment]
I think 'than' is superfluous in all cases. "Otherwise" is correct, or "other than" is correct.

**Comment by Jean-LouisMesic** [comment]
Well done, @terrorist96 ! Good catch.

**Pull request closed without merging**
