### PR TITLE
eleven/fifteen

### PR DESCRIPTION
**Pull request by FellowTraveler**
I changed *"vote of eleven"* to be *"vote of a majority of all Assembly Representatives."*

I also changed *"vote of fifteen"* to be *"vote of three-quarters of all Assembly Representatives."*

NOTE: this PR does *not* change the operation of the Constitution at all. **The behavior is identical.** The purpose of this PR is to make it easier later to make changes in §IV.2 with a future pull request.

This PR stands on its own, and since it doesn't change the functionality of the Constitution in any way, it should be fine to merge it. This way any future debate can occur when a future PR is submitted for §IV.2, and it won't require changes all over the Constitution, but will localize any changes to that specific provision.

### CODE REVIEW

**Comment by KacperZajc** [comment]
I understand the purpose, I dont mind :)

**Comment by KacperZajc** [comment]
wait that poses a problem:
this either make it necessary for all representatives to attend the meeting OR allows to pass with a majority of representatives present, no matter how many of them it is
am I right?

**Comment by FellowTraveler** [comment]
The idea is to make it behave the same as before, without having to state the number.

For example, if there are 20 representatives, then the "majority of ALL representatives" would be 11. This doesn't mean that all 20 actually have to attend the meeting, but it does mean that at least 11 of them must vote for the provision.

Someday in the future, let's say there are 50 representatives. In that case, the "majority of ALL representatives" would be 26. This doesn't mean that all 50 actually have to attend the meeting, but it does mean that at least 26 of them must vote for the provision.

**Comment by KacperZajc** [comment]
aaah ok this interpretation makes sense

**Comment by cnavigato** [comment]
interesting change, well thought out ;)

**Pull request merged**
