### PR TITLE
Appointing of The Chef Public Prosecutor #93

### PR DESCRIPTION
**Pull request by saintego**
Maybe life period is too long and 4,5 or 6 years would be better

### CODE REVIEW

**Comment by saintego** [comment]
I wanted to open discussion, because I think Constitution should have that point in the way it is written

**Comment by KacperZajc** [comment]
I agree it needs discussion, I want to hear your opinions here.

**Comment by liberlandcitizen** [comment]
Term limits seem reasonable for all public offices with power.

**Comment by saintego** [comment]
I think it's general practice that prosecution have different period with government(so 5 or 7 years)  but I think everything depends on power of prosecutor. Will he be able to cover crime by not to process it to court?

**Pull request closed without merging**
