### PR TITLE
§III.3

### PR DESCRIPTION
**Pull request by liberty90**
* **§III.3.** As weird as this may seem, "degrading treatment" sometimes may be voluntary. BDSM, for example; but also - arguably - military boot camps etc.

### CODE REVIEW

**Comment by KacperZajc** [comment]
technically you are right but in this context it is implied - the phrase I used is widely used, especially in international law and has a particular meaning

**Comment by joshmh** [comment]
@liberty90 brings up a good point. What may seem obvious is current context does not always carry through over time. There are lots of examples of that in the US constitution. I'd prefer to make it more explicit.

>  **§III.3.** No involuntary torture and no cruel, unusual, or degrading treatment shall be inflicted on any person without his or her consent by any member of any branch of the Public Administration or with consent or knowledge thereof; no person shall be subjected to experiments of any sort without his or her consent. Any person, regardless of position in the Public Administration, shall be held accountable for such a crime, regardless of any law, policy, command or suggestion claiming to authorize the deed.

**Comment by KacperZajc** [comment]
ok we can modify if you want but involuntary must go after torture because torture by definition cannot be voluntary;
I like the idea of adding responsibility clause
here is how I see it:

§III.3. No torture or other involuntary cruel, unusual, or degrading treatment shall be inflicted on any person by any member of any branch of the Public Administration or with consent or knowledge thereof; no person shall be subjected to experiments of any sort without his or her consent; any person whatsoever responsible shall be held personally accountable for such a crime against human dignity, regardless of any law, policy, command or suggestion which might have been authorising such conduct.

???

**Comment by joshmh** [comment]
Oops, I meant to leave out "involuntary". The idea was to replace that with "without his or her consent," since that's more consistent with the second half, and since "involuntary" could be construed as the state agent involuntarily inflicting cruel treatment. So:

> §III.3. No torture or other cruel, unusual, or degrading treatment shall be inflicted on any person without his or her consent by any member of any branch of the Public Administration or with consent or knowledge thereof; no person shall be subjected to experiments of any sort without his or her consent; any person whatsoever responsible shall be held personally accountable for such a crime against human dignity, regardless of any law, policy, command or suggestion which might have been authorising such conduct.

**Comment by KacperZajc** [comment]
that is acceptable but torture without consent sounds a bit ridiculous

**Comment by KacperZajc** [comment]
ok Im changing that

**Pull request closed without merging**
