### PR TITLE
fix

### PR DESCRIPTION
**Pull request by terrorist96**
Removed 'scheduled and completed' because it broke the sentence structure

### CODE REVIEW

**Comment by terrorist96** [comment]
Also, this is the only provision which contains a serial comma whereas it's been avoided in all other provisions. I don't think it can be avoided due to the wording of this provision and it breaks the consistency. :disappointed:

**Comment by KacperZajc** [comment]
I think this part is important, can you come up with wording which would encompass this bit yet sound better than mine?

**Comment by KacperZajc** [comment]
how about:

§VIII.5. The Public Administration shall (a) record and transmit video and audio of, (b) publish and archive documents of, and (c) render available to the general public to attend, all affairs of the Assembly and all proceedings before the Courts other than those concerned with Warrants, **both scheduled and completed**; all documents officially produced by any Member of the Cabinet shall also be published within twenty-four hours; nothing in this provision shall prevent the Public Administration from protecting information classified as a state secret, including the debate and vote on such a classification.

**Comment by terrorist96** [comment]
@KacperZajc ready for merge

**Pull request merged**
