### PR TITLE
Add transifex support for language translations. Add an initial, mostly empty, czech translation

### PR DESCRIPTION
**Pull request by lunokhod**
**This pull request adds Transifex support for translations**

Transifex is an online service that allows a project to upload a source file from a git, to have this source file translated by community members, and then to pull the translation back into the git project. Transifex is a free service for open source projects, and the Liberland project can be found [here](https://www.transifex.com/organization/liberland/dashboard/constitution). At this point I have added only the "constitution" project, but if this pull request is accepted, I will add similar projects for "laws" and whatever else requires it.

This pull request adds a directory ".tx" which contains the transifex configuration file, and adds a directory "translations" which contains the initial Czech translation "Liberland-constitution_cs.md" (I simply copy-pasted the first two lines from the translations project).

To use Transifex, create an account on their [web site](https://www.transifex.com/). Send me a message, and I will add you to the project. Any member on this git will be given full privileges. Next go to the [Liberland dashboard](https://www.transifex.com/organization/liberland/dashboard/constitution), click on the Czech "strings to be translated", and then click on "constitution". The rest should be obvious/idiot proof.

To pull an updated translation file into this git, you will first need to install the transifex client. On OSX, I needed to use the most up to date beta

    pip install transifex-client==0.11.1.beta

To pull the file from transifex into git, use

    tx pull -a

To push a modified source file to transifex, use

    tx push -s

If you modifiy the source and translation files directly in git, and wish to push it to transifex, use

    tx push -t -s

If there are any questions, just contact me. I am more than willing to coordinate this activity.

### CODE REVIEW

**Comment by KacperZajc** [comment]
Im afraid I am not in charge of IT stuff, please contact one of our specialists :)

**Comment by lunokhod** [comment]
The first question is: Do you want to translate the constitution and have the translation files in the directory "/translations"? If you are not familiar with Transifex, I simply note that this is what Bitcoin and many other open source projects use.

Presuming that you agree with this approach: I am willing to merge this pull request into the project, and manage the translation effort. However, to do this, I will need to be added to the project and given write access. I am in change of the Transifex translation project for Anoncoin, so I am familiar with how to do this. 

If you are uncomfortable with giving me write access, could you please let me know who to contact? thanks! Feel free to contact me via email if you have any questions: lunokhod@i2pmail.org

**Comment by lunokhod** [comment]
The transifex translation project is live: 
http://www.reddit.com/r/Liberland/comments/3aec6i/help_liberland_translate_documents/

**Comment by KacperZajc** [comment]
please e-mail kreibich@mediasun.cz for all IT enquiries :)

**Pull request closed without merging**
