### PR TITLE
Otherwise than vs other than

### PR DESCRIPTION
**Pull request by terrorist96**

### CODE REVIEW

**Comment by Jean-LouisMesic** [comment]
@terrorist96  The wording for **§IV.16.** is correct, as it allows the cabinet to revise a rejected bill ONLY by resubmitting it the next year, and by no other means. "Otherwise than by" is the way to say this.

The wording of **§III.10.** is odd, I agree. Deserves discussion. I think your fix is sufficient, but perhaps not.

**Comment by terrorist96** [comment]
I think you're right about IV.16

**Comment by KacperZajc** [comment]
ok make a new pull here

**Comment by terrorist96** [comment]
Is the "fixed IV.16" PR not good?

**Comment by KacperZajc** [comment]
I can’t automatically merge this pull request.

**Pull request closed without merging**
