### PR TITLE
fully-informed juries

### PR DESCRIPTION
**Pull request by FellowTraveler**
This PR continues the discussion from https://github.com/liberland/constitution/pull/55

### CODE REVIEW

**Comment by KacperZajc** [comment]
I think I agree with this, what do you all think guys?

**Comment by KacperZajc** [comment]
I fine with this wording if you remover 'based on personal conscience' part

**Comment by FellowTraveler** [comment]
> I'm fine with this wording if you remove 'based on personal conscience' part

What if the judge instructs you to convict if you find the facts, but you feel really really bad about doing it because you honestly believe the defendant has done nothing wrong? What if you honestly believe the law itself is wrong?

Imagine if the judge says, "If you find that grass is green, you must punch a baby in the face." Imagine that you really really don't want to punch a baby in the face, and it would make you feel really bad, but you feel that you have no choice, because the judge has instructed you to do so.

You don't have a right to vote your conscience? Isn't that the whole reason we have a jury in the first place, as a last line of defense to protect the people from abusive laws?

**Comment by KacperZajc** [comment]
It still leaves the part where it allows to acquit - so no matter what are the reasons the right to acquit remains.
I oppose 'personal conscience' because that doesnt sound like a legal principle, even if I agree with the substance I want to 'smuggle' it under another name - the general right to acquit.

**Comment by FellowTraveler** [comment]
How about "retains the unequivocal right to acquit based on conscience, and shall be informed of this right."

(Removes "personal.")

For some legal justification:

In his trial Nazi war criminal Adolf Eichmann claimed he was simply following legal orders under paragraph 48 of the German Military Code which provided: "punishability of an action or omission is not excused on the ground that the person considered his behaviour required by his conscience or the prescripts of his religion". (German law forced Nazis to ignore their conscience, but this did not excuse them in Nuremberg.)

The United Nations Universal Declaration on Human Rights (UDHR) which is part of international customary law specifically refers to conscience in Articles 1 and 18. Likewise, the United Nations International Covenant on Civil and Political Rights (ICCPR) mentions conscience in Article 18.1.

All human beings are born free and equal in dignity and rights. They are endowed with reason and *conscience* and should act towards one another in a spirit of brotherhood
—United Nations, Universal Declaration on Human Rights Article 1

Everyone has the right to freedom of thought, *conscience* and religion; this right includes freedom to change his religion or belief, and freedom, either alone or in community with others and in public or private, to manifest his religion or belief in teaching, practice, worship and observance
—United Nations, Universal Declaration on Human Rights Article 18

Everyone shall have the right to freedom of thought, *conscience* and religion. This right shall include freedom to have or to adopt a religion or belief of his choice, and freedom, either individually or in community with others and in public or private, to manifest his religion or belief in worship, observance, practice and teaching
—United Nations, International Covenant on Civil and Political Rights Article 18.1

Good enough?

**Comment by KacperZajc** [comment]
"retains the unequivocal right to acquit, and shall be informed of this right."

Im fine with 'unequivocal '

Im not fine with conscience because this of the reasons I mentioned.

What is sb says his religion through his conscience tells him to acquit a defendant who went on jihad and killed 40people in a terrorist attack (no offence to any Muslims intended)?

This approach is too dangerous, conscience is a very relative concept, too relative for a legal system if we emphasise its importance. It will always play some role but we cant put in the first row.

**Comment by FellowTraveler** [comment]
Okay I will remove the "conscience" part because it's important to get the rest of the wording in there.

We can pick it up in a separate PR.

**Comment by FellowTraveler** [comment]
@KacperZajc Okay I removed the conscience line, we can pick it up in a separate PR. I think you can merge this one now.

**Comment by FellowTraveler** [comment]
@cpacia This PR was important because it says the Jury must be "informed" of their unequivocal right to acquit.

> The way it reads now, it seems like the status quo where the judge decides what the law is and the jury has to enforce it even if it's a violation of people rights.

Yes I know. It's actually surprising to me that this is even in dispute since jury nullification is such a huge issue in the United States. Possibly the number-one most important Libertarian issue, yet I am having trouble getting it into a "Libertarian" Constitution!

Anyway, I'm going to submit a separate PR for "conscience" so we can continue the discussion there. This issue, plus "fair representation" are the two most important ones I think and I'm getting a lot of pushback on both of them. Not good.

**Comment by FellowTraveler** [comment]
The new PR is #344

**Pull request merged**
