### PR TITLE
require that the PPO receive a complaint

### PR DESCRIPTION
**Pull request by tinkyholloway**
It's not the job of the PPO to go around looking for work to do, instead their work starts with a complaint

### CODE REVIEW

**Comment by cpacia** [comment]
+1 this is similar to issue #8.

**Comment by joshmh** [comment]
I agree with the sentiment, but I don't think this change will work as intended. The prosecutor will always be able to get someone to file a claim. So, I prefer https://github.com/liberland/constitution/issues/8.

**Comment by tinkyholloway** [comment]
I agree that this is much better handled in #8

**Comment by KacperZajc** [comment]
there will be offences for which a complaint is necessary to prosecute and some which will be prosecuted automatically - anyway this is not an issue that should be included in the Constitution

**Comment by KacperZajc** [comment]
no need for change

**Pull request closed without merging**
