### PR TITLE
Added taxation to legislative restrictions section

### PR DESCRIPTION
**Pull request by terrorist96**
Also added a period to the end of II.17

### CODE REVIEW

**Comment by Jean-LouisMesic** [comment]
@terrorist96 I like this rework. +1

**Comment by KacperZajc** [comment]
we dont touch taxation at this point but if it stays for good, we will get back to your pull :)

**Comment by terrorist96** [comment]
I made a separate PR for the period at the end of II.17

**Comment by terrorist96** [comment]
Please keep this open. Since the tax bill is already in the current draft, this change should be made.

**Comment by KacperZajc** [comment]
but what you want to introduce is already said in any event

**Comment by terrorist96** [comment]
Yeah but the wording is awkward

**Comment by Jean-LouisMesic** [comment]
I like his rewording, it doesn't change anything, but makes it more concise. It also puts the legislative restrictions on taxation where they belong.

**Pull request closed without merging**
