### PR TITLE
Update Liberland-constitution.md

### PR DESCRIPTION
**Pull request by terrorist96**
Changed `permission` to `express and informed consent` and added `implied` prior to `consent`.

### CODE REVIEW

**Comment by KacperZajc** [comment]
shouldnt that be specified by ordinary law?

**Comment by terrorist96** [comment]
Why can't it be defined in the constitution?

**Comment by KacperZajc** [comment]
Im just afraid of this 'implied' consent part?

**Comment by terrorist96** [comment]
Ok I changed it for now.

**Pull request merged**
