### PR TITLE
clarify that the cabinet is formed from Assembly members

### PR DESCRIPTION
**Pull request by tinkyholloway**
as opposed to anyone that the Assembly deems fit to elect as Chancellor and anyone the Chancellor deems fit to nominate to the Cabinet.

### CODE REVIEW

**Comment by KacperZajc** [comment]
I dont think it should be formed from representatives only, it should be formed from experts and those will be very often outside of the assembly

**Comment by KacperZajc** [comment]
no need for change

**Comment by tinkyholloway** [comment]
If Cabinet members are drawn from the citizenry then should this be clarified in the wording? Something like 'from the Citizenry'. Are you proposing non-Citizens as well?

**Comment by KacperZajc** [comment]
we can clarify that Cabinet is formed from citizens;
but not necessarily from Assembly Representatives

**Comment by tinkyholloway** [comment]
No argument from me. I was more interested in the clarification than I was for one way or another.

**Pull request closed without merging**
