### PR TITLE
Rationale

### PR DESCRIPTION
**Pull request by fare**
Here's a pull request with your wording from #30.

I believe the current wording isn't enough, because it doesn't make the rationale and budget binding; these two items are toothless without an explicit mention of nullification when they are lies.

### CODE REVIEW

**Comment by KacperZajc** [comment]
your version is too broad and allows to strike down the law on by any court in any circumstances because it is impossible to define the terms you have used

**Comment by fare** [comment]
Well, nullification IS the striking down of bad laws by any court.

But the more general point is that there needs be a strong filter against bad law that cannot be easily captured by an establishment. If interpreting the constitution is left to those meant to be stopped by the constitution, it won't be long until the supreme court is stuffed with friends of the Establishment, and it's game over.

**Comment by KacperZajc** [comment]
and that is exactly why I put the clause which enables citizens to impeach the judges of the supreme court :)

**Comment by fare** [comment]
Then the wording could be that citizens can seize the supreme court (rather than any court) based on obsolete/invalid/unmet rationale, inefficient means, excessive budget, unintended consequences, etc.

**Comment by KacperZajc** [comment]
these are all to vague, this will not be a rule of all if you can revolt because there were unintended consequences

**Comment by fare** [comment]
Well, you still need the supreme court to agree, and you don't revolt, just strike down the bad law. Example recent such bad law: http://fee.org/anythingpeaceful/detail/israel-puts-price-controls-on-books-devastates-sales

**Comment by KacperZajc** [comment]
but we limited the areas of competence of the assembly so that such cases wont happen

**Comment by fare** [comment]
Belts and suspenders are better than either alone. If you want to make your constitution robust, you shouldn't trust a single mechanism. If you want to trust the government, just declare an absolute monarchy and be done (that's something I respect, too). But a constitution that doesn't have much in terms of tooth is just a decorative document. Hell, some people used to say that the Soviet Union had a great constitution, protecting the rights of people, etc. — except their only recourses were all parts of the same establishment.

**Comment by KacperZajc** [comment]
please, implying that I trust the gov is offensive
but what is proposed here is absolutely unworkable, it's too broad and too vague, it simply cannot be put in the Constitution

**Comment by fare** [comment]
So my pull request is currently as you proposed:

* **§II.18.** No Bill proposed to the Assembly shall be passed unless it has been read aloud in entirety by the Assembly Speaker and includes precise calculation as to its potential impact on the budget as well as rationale behind it and means of achieving thereof, which does not conflict with the Constitution.

I propose to amend it to add something like:
Citizens may seize the supreme court to strike down laws that do not or no longer adequately and efficiently meet their legitimate declared rationale with their means.

**Comment by KacperZajc** [comment]
this is crazy, Im sorry guys but this is equivalent to setting up a revolutionary tribunal in China or Cuba...

**Comment by fare** [comment]
What is the supreme court for, then? Sometimes, the law looks good, but a year later is found to be bad. If the supreme court can only strike it down initially, it's too late.

There's no revolutionary tribunal. No one is sent to camp or forced to do daily self-criticism. It's just about having redundant ways of striking down bad laws.

**Comment by fare** [comment]
No one wants to remove laws that everyone agrees upon.

**Comment by KacperZajc** [comment]
but I can offer something less ridiculous:

in bill of rights part:

§II.18 No Bill proposed to the Assembly shall be passed unless it has been read aloud in entirety by the Assembly Speaker and includes precise calculation as to its potential impact on the budget as well as rationale behind it and means of achieving thereof.

in judicial power part:

It shall be the duty of any Court of the Free Republic of Liberland to strike down any law as obsolete if its effect no longer corresponds with the rationale declared behind it under §II.18.

what do you think?

**Comment by KacperZajc** [comment]
this would add another ground for striking down a law (apart unconstitutionality) 
and it would at the same time deal with your request for sunset clauses - no obsolete law will be effective anymore

**Comment by fare** [comment]
Yes, putting it in a separate article about the judiciary is indeed much better.

Can you word it either so that "rationale" includes the budget, or that the striking down can be done not just on rationale as desired benefits/goal, but also on based on costs/means/budget become too big or unadapted?

Sometimes the benefits still exist, but the costs have skyrocketed. Or some unintended costs arise, etc., that once accounted make the *existing* benefits not worth it.

**Comment by KacperZajc** [comment]
in bill of rights part:

§II.18 No Bill proposed to the Assembly shall be passed unless it has been read aloud in entirety by the Assembly Speaker and contain rationale behind it and means of achieving thereof including precise calculations as to its potential impact on the budget.

in judicial power part:

It shall be the duty of any Court of the Free Republic of Liberland to strike down any law as obsolete if its effect no longer corresponds with the rationale behind it as declared under §II.18, considering the accuracy of the initial budget calculations and effectiveness of means adopted.

**Comment by KacperZajc** [comment]
in bill of rights part:

§II.18 No Bill proposed to the Assembly shall be passed unless it has been read aloud in entirety by the Assembly Speaker and contain rationale behind it and means of achieving thereof including precise calculations as to its potential impact on the budget.

in judicial power part:

It shall be the duty of any Court of the Free Republic of Liberland to strike down any law as obsolete if there is a significant disparity between the effect of the law and the rationale behind it as declared under §II.18, considering the accuracy of the initial budget calculations and the effectiveness of means adopted.

**Comment by Zephram-C** [comment]
Sorry to enter discussion late, but...
Isn't it usually difficult to formulate Rationale unambiguously? I see big space for Court subjective view and interpretation in *significant disparity between the effect of the law and the rationale behind it*. Adherence to the Constitution is more objective. Also *precise calculations* might be difficult. It is almost impossible to precisely plan for the future prices and costs.

**Comment by fare** [comment]
You don't need precise calculations or unambiguous goals to strike down laws that are blatantly off the mark in terms of cost/benefit and/or completely unattained goals. Especially when most "laws" in the US quite clearly achieve the *opposite* of the stated goal. Erecting in the constitution good principles of economic analysis of law and their violation as reason enough to strike them down is important.

**Pull request closed without merging**
