### PR TITLE
Small change to gun ownership

### PR DESCRIPTION
**Pull request by Auahi**
* **§II.23(1)** Any Individual who has been proven guilty of a felony shall have the following rights revoked: to own, manufacture, sell, transfer, transport, bear and use any small arms, arms accessories, or ammunition, be they now historic, contemporary and/or experimental, regardless of condition.

this was my old proposal: disregard this one, the one on top is worded better and without my typo lol
  * **§II.23(1)** Any Individual who has been proven guilty of a felony shall have the the right to own, manufacture, sell, transfer, transport, bear and use any small arms, arms accessories, or ammunition, be they now historic, contemporary and/or experimental, regardless of condition revoked.

People committed of felonies shouldn't be trusted with a gun. List of felonies in Liberland: https://liberland.org/en/laws/

### CODE REVIEW

**Comment by terrorist96** [comment]
Am I reading this wrong?

**Comment by Auahi** [comment]
Read it as though it was this:
Any Individual who has been proven guilty of a felony shall have the the right to own arms revoked, the right to manufacture arms revoked, to sell arms revoked and so on, I just copy the main part from §II.23 and put revoked at the end, I think it would be redundant to put revoked at the end of everything...

I could change it to this:

§II.23(1) Any Individual who has been proven guilty of a felony shall have the following rights revoked: to own, manufacture, sell, transfer, transport, bear and use any small arms, arms accessories, or ammunition, be they now historic, contemporary and/or experimental, regardless of condition.

And I'm going to have to change it anyways since it has a typo

**Comment by terrorist96** [comment]
Putting revoked earlier on is much more clear. Though I don't know if we need this section since it was my understanding that non-individuals include criminals.

**Comment by Auahi** [comment]
Oh okay, and if thats true then you're right, I didn't read that about felons in the constitution, if it isn't in it you should make a pull for that

**Comment by terrorist96** [comment]
> incarcerated following a conviction in a court of law

So seems like it only includes felons behind bars. Felons who have served their time and have regained their freedom to live amongst society count as individuals.

**Comment by Auahi** [comment]
Oh yeah you're right, I was just going to post §I.8.

**Comment by Auahi** [comment]
@KacperZajc what do you think?

**Comment by KacperZajc** [comment]
@terrorist96 is right.
I dont think we need to deprive ex cons of their right to bear arms, they would get guns anyway.

**Comment by Auahi** [comment]
Yes they could get guns but this would make it harder for them, i think @terrorist96 was just saying that the law about felons being non-individuals only applys to them if they are in in prison.

I still think tjough that someone who commited agravated assault shoulnt  be able to own a gun, theres just to much of a risk to the public with someone who is violent to just easily give them back a gun. Plus this would make it if a cop found the felon with a gun they could be arrested for just having it, simce it would be illegal for them to get it...

**Comment by KacperZajc** [comment]
In theory you are right. In practice this would require complex laws and regulations and in would turn out unenforceable in any event. Just no point bothering.

**Comment by Auahi** [comment]
I dont know where you live, but where i live in the US they have the most complicated gun laws(I live in New Jersey). I would never want to model gun laws how the US does. We have guns in my house and yes there are many regulations but i think i have a way to simplify it.

Inorder to buy a gun you must prove that you have a record clean of felonies. To do this just go to the police station and they could give you a document which is valid for 6 months which prooves this and allows you to buy any number of guns...

So you wouldnt have to fill out complicated paperwork, just get a simple document from police stating that youre clean...

I dont think this would be bad, how about you

**Comment by KacperZajc** [comment]
@terrorist96 what do you think?

**Comment by terrorist96** [comment]
> I live in New Jersey

My condolences.

My thoughts are conflicting. On one side, I don't want violent felons to be able to get guns legally due to a high rate of recidivism, but on the other hand, they have served their time and have regained their freedom to live amongst society and should regain their rights. If they are truly dangerous, they shouldn't be living with the rest of society.

**Comment by Auahi** [comment]
You also have to look at it this way, the US and most countries have a mass majority of people in jail for non-violent crimes, most of these crimes are drug related, in Liberland these people who were in jail for felonies went for violent crimes not for little petty things

**Comment by terrorist96** [comment]
Yes, that's why I mentioned violent felonies in particular. I don't know what the rate of recidivism is for violent felonies versus non-violent felonies.

**Comment by KacperZajc** [comment]
I just dont like this idea that you have to go to the police for confirmation that you can buy a gun. It is against everything we do here.

**Comment by Auahi** [comment]
Yes true i see what you mean maybe an online thing instead... Any you could print it out, and it has a number on it who the gun dealer checks...

I found these statistics:

Bureau of Justice Statistics studies have found high rates of recidivism among released prisoners. One study tracked 404,638 prisoners in 30 states after their release from prison in 2005.[1] The researchers found that:
Within three years of release, about two-thirds (67.8 percent) of released prisoners were rearrested.
Within five years of release, about three-quarters (76.6 percent) of released prisoners were rearrested.
Of those prisoners who were rearrested, more than half (56.7 percent) were arrested by the end of the first year.
Property offenders were the most likely to be rearrested, with 82.1 percent of released property offenders arrested for a new crime compared with 76.9 percent of drug offenders, 73.6 percent of public order offenders and 71.3 percent of violent offenders.

**Comment by Auahi** [comment]
A 71.3% for violent crimes is not a good percentage at all

**Comment by terrorist96** [comment]
> 71.3 percent of violent offenders

So they were violent offenders, and ended up getting arrested again, but it doesn't say if they were arrested for violent offences or something else.

Here's a better idea: people who we consider disqualified to own arms should be added to a list (think sex offender registry). Before a dealer can sell arms to a person, it can check to see if the person buying is on that list. This way, the person buying doesn't have to prove that they are qualified, instead the person selling has to prove they are disqualified.

**Comment by KacperZajc** [comment]
I thought of that but how do you reconcile that with our personal data laws?

**Comment by Auahi** [comment]
Okay i like that idea

**Comment by terrorist96** [comment]
> personal data laws

They've already been in jail and had a number assigned to them. Same for mentally ill people - they've already been involuntarily admitted to a psychiatric ward, which would assign them a number. Personal data laws wouldn't apply.

**Comment by Auahi** [comment]
I agree @terrorist98 

And it says  pursuant to a warrant... They have a warrant already attached to them and the name can be in the warrant details...

**Comment by Auahi** [comment]
@KacperZajc what do you think of all this?

**Comment by yopdog** [comment]
If we take away the right to own guns from ex-felons then it would also logically follow that we should take away their right to own knives, drive cars, fly planes, cook food for others, etc. At this point, we may as will put them back in jail since they are clearly a danger to the public. My point here is that once it is decided that they can be released, it makes no sense to restrict some of their rights for fear of them killing someone since that was the very condition that got them released in first place. In order to kill or hurt someone you have to be really really crazy. Guns are simply one out of many tools for achieving such a thing.

**Comment by Auahi** [comment]
I disagree completely!
The following murder statistics are for the US in 2011
8583 people were killed by Guns
1694 people were killed by Knives
About 300 were killed via vehicular homicide
5 by poison
and if people were killed by deliberate plane crashes via x-cons that would be considered terrorism so we have big problems if that happens...

Guns have killed the most people by far, so why not limit this tool to people who have been known to harm others?

Also this sentence is not correct "My point here is that once it is decided that they can be released, it makes no sense to restrict some of their rights for fear of them killing someone since that was the very condition that got them released in first place." People are not released because they are no longer deemed a nuisance to society rather because the judge chose to set a time based upon the crime one committed, the judge doesn't go back an review progress on people decide if they can be released or not.

Another thing, most people who are released from jail return: Property offenders were the most likely to be rearrested, with 82.1 percent of released property offenders arrested for a new crime compared with 76.9 percent of drug offenders, 73.6 percent of public order offenders and 71.3 percent of violent offenders. this proves that just because they were released doesn't mean they'll follow the law. and I know it doesn't tell you exactly why they were rearrested but it still shows that they are way more likely to be arrested again...

**Comment by Auahi** [comment]
@yopdog 

I disagree completely!
The following murder statistics are for the US in 2011
8583 people were killed by Guns
1694 people were killed by Knives
About 300 were killed via vehicular homicide
5 by poison
and if people were killed by deliberate plane crashes via x-cons that would be considered terrorism so we have big problems if that happens...

Guns have killed the most people by far, so why not limit this tool to people who have been known to harm others?

Also this sentence is not correct "My point here is that once it is decided that they can be released, it makes no sense to restrict some of their rights for fear of them killing someone since that was the very condition that got them released in first place." People are not released because they are no longer deemed a nuisance to society rather because the judge chose to set a time based upon the crime one committed, the judge doesn't go back an review progress on people decide if they can be released or not.

Another thing, most people who are released from jail return: Property offenders were the most likely to be rearrested, with 82.1 percent of released property offenders arrested for a new crime compared with 76.9 percent of drug offenders, 73.6 percent of public order offenders and 71.3 percent of violent offenders. this proves that just because they were released doesn't mean they'll follow the law. and I know it doesn't tell you exactly why they were rearrested but it still shows that they are way more likely to be arrested again...

**Comment by yopdog** [comment]
>Guns have killed the most people by far, so why not limit this tool to people who have been known to harm others?

First of all, guns don't kill, people kill. Limiting access to one tool isn't  going to reduce homicide since there are always going to be other ways in which a person can kill. The statistics you brought up from fbi.gov only prove my point that guns are just one of many tools that can be used for killing. The fact that guns may be the most popular option says nothing about whether they encourage people to commit violent crimes.

Concerning the part about people being released, you are right about the fact that that's not how it works in most countries, but it's how I believe it should work in Liberland. The government is going to be run on a very small budget, and it will only make sense to incarcerate those who pose a real danger to the public. Incarcerating someone as a punishment only acts as a burden for everybody else who has to pay for his Incarceration. Once a person is released he should regain all his rights. trying to limit some of his rights in order to prevent recidivism is a frivolous game that will achieve nothing         

My biggest problem with this change is that it will introduce a lot of bureaucracy while achieving very little. Criminals will always be able to find what they need to commit their crimes. If they can't get a gun legally they can just find a person who will sell it to them anyway. Alternatively, they can just use a knife which has been the weapon of choice for thousands of years before guns were invented. The end result will be a reduction in people's freedom to sell and buy guns. All for a false sense of security.

**Comment by KacperZajc** [comment]
I agree with @yopdog, it's just not worth the effort IMO

**Comment by Auahi** [comment]
First off, I'd argue that limiting guns will bring down murder rates,

Guns are very different tools than knives, you can't commit mass murder with a knife like you would with a gun. Guns unlike knives have a reach far longer than a persons arm(yes you can throw a knife but to throw one accurately takes a lot of practice).

Like we said early this won't limit guns to people who haven't committed felonies at all! It's actually a very simple system, if your name isn't on a list then you'll have no problem purchasing a gun...


One more point is that Croatia Serbia and most countries in the world take Liberland as a joke, but they'd take liberal and as a threat also if it had no gun control whatsoever, no country would want to be next to another if anyone no matter what could get a gun! This would help Liberland be a little more appealing to other nations, remember what Croatia said, they didn't want liberland to be a nation full of junkies and be a threat to the Croatian border(the people).

**Pull request closed without merging**
