### PR TITLE
double jeopardy

### PR DESCRIPTION
**Pull request by FellowTraveler**
Removed "unless new evidence of high relevance came to light".

The reason is twofold:

1. This exception is very dangerous as it allows the government to get their foot in the door to violate double jeopardy. Anytime they can construe they came up with "new evidence" they will re-try defendants who have been acquitted. This will be used selectively against targeted defendants and destroys the "final acquittal" power of the jury.

2. Historically this "unless new evidence" provision has not been necessary. We have seen that the double-jeopardy provision in the US Constitution has been very effective and has not required any "unless new evidence" provision, and yet prosecutors have still effectively been able to get convictions and plea bargains. Therefore there is no need to weaken the double-jeopardy protections.

### CODE REVIEW

**Comment by jasoneriksen** [comment]
:+1:

**Comment by KacperZajc** [comment]
yeah that was the original wording I changed it afterwards because many people on FB suggested that, Im still not sure which way to go

**Comment by FellowTraveler** [comment]
Double jeopardy is one of the things about the U.S. Constitution that works well. I would really hesitate to add a dangerous new exception like this.

**Comment by KacperZajc** [comment]
ok we need to think about that

**Comment by joshmh** [comment]
:+1:

**Comment by KacperZajc** [comment]
no, I dont know why it shows it here.
I removed the drug protection today because the President said it was unsustainable because of PR (see a separate issue on that).

**Comment by FellowTraveler** [comment]
I'm closing this pull request and adding a new one, since the rebase caused merge problems.

**Comment by FellowTraveler** [comment]
Discussion continued here: https://github.com/liberland/constitution/pull/71

**Pull request closed without merging**
