### PR TITLE
Fully-informed Jury nullification.

### PR DESCRIPTION
**Pull request by FellowTraveler**
Added the right of the Jury to nullify the law. See Indiana state constitution. Also added right of Jury to be informed of its power to nullify the law.

### CODE REVIEW

**Comment by KacperZajc** [comment]
we discussed the possibility of determining law earlier -  I dont think it is a good idea because they are not qualified, they should be directed by the judge as to the law and determine facts;
plus if the believe the law is unfair as it stand they can acquit in any event and this is irreversible decision so nullification is guaranteed even if they decide about facts only.

right to be informed about the power to acquit is self-evident

**Comment by FellowTraveler** [comment]
The right to be informed about the power to acquit may be self-evident, but in America many juries are completely uneducated about their power to nullify bad law.

The Fully-Informed Jury Association has been fighting this battle for years since the judicial system is very hostile towards efforts to inform juries of their rights.

I would even make the wording more explicit and say the jury has the ability to rely on personal conscience, to judge the merit of the law and its application, and to nullify bad law, when necessary for justice, by finding for the defendant.

Otherwise history has already proven that juries will be misled by judges into believing that they must convict based on the law even if the law is unjust.

**Comment by KacperZajc** [comment]
well they should convict even if the law is 'unjust' as long as it is constitutional;
we cannot introduce the idea of nullifying 'unjust laws' because this term is so vague that it means nothing and something different for everyone;
They have the right to acquit and no questions will be asked so there is no reason to allow only 'just' laws to be binding because this is no longer law - it is morality and you cant base the judicial system on morality.
we made a provision that acquittal by jury is final so this protects the verdict

**Comment by FellowTraveler** [comment]
> well they should convict even if the law is 'unjust' as long as it is constitutional

So if the 12 members of the Jury all believe that a horrible injustice is being perpetrated upon the defendant by a bad law, then they should convict anyway? Even when they cannot in good conscience bring themselves to convict? They should convict anyway?

If they do have the right to acquit in this situation, where they think the law is wrong, they should be explicitly informed of this right. Otherwise, history has shown that courts will misdirect juries and mislead them, to hide this power from the jury and so prevent them from exercising it.

**Comment by FellowTraveler** [comment]
BTW, the purpose of the jury is not solely to determine if the defendant has broken a specific law. Rather, the purpose of the jury is to acquit if they believe the defendant is innocent of wrongdoing -- regardless of whether the defendant broke the law. The purpose of the jury is to protect defendants against bad law.

**Comment by KacperZajc** [comment]
by forbidding the creation of victimless crimes, we excluded the possibility of making really 'unjust laws' to some extent;
you cannot based the administration of justice on the idea that a person is not guilty because the law was not good - this can be interpreted differently by everyone 
there will be no certainty of what is and what isnt a crime anymore

**Comment by KacperZajc** [comment]
I sure that if there was a really unjust law, the jury would acquit under the current wording

**Comment by FellowTraveler** [comment]
> I am sure if there was a really unjust law, the jury would acquit under the current wording

Yes IF they are aware of their right to do so.

Often judges lie to Juries and tell them that they must convict only based on the facts. Juries then end up convicting defendants even when they didn't want to convict. They didn't realize they had the power because the court lied to them about it and persecuted anyone who tried to inform them. This is why there is a Fully-Informed Jury Association in America. This issue alone has resulted in many unjust convictions and enabled much government encroachment on rights.

**Comment by joshmh** [comment]
I agree with @FellowTraveler here. These are not academic arguments, all one has to do is check what is actually happening in the US. Jury nullification is almost non-existent, so we needn't worry too much about too much nullification. Instead, we should encourage it, to promote a better balance of power. In the one case I'm aware of in New Hampshire, nullification was used to exonerate an old man who was growing marijuana for his own use, on his own property. Clearly not something we have to be afraid of.

**Comment by naconner** [comment]
The United States Constitution has explicitly forbade the creation of laws limiting free speech, warrantless searches, the rights of people to keep and bear arms, etc. However, as clear as they are, words on paper have not prevented such unjust laws from being passed and enforced.

The people's right to vote their conscience in a jury box is the last check on unjust laws. It is the ultimate veto. If we cannot trust the people to use their conscience to decide what's right or wrong, then that society is lost.

@KacperZajc, you're right in that the current wording would not prohibit jurors from voting 'not guilty' based on conscience, however, as @FellowTraveler noted, judges have routinely misdirected jurors on their right to do so. To enshrine this in the Constitution would be a huge step forward in ensuring that injustice is not carried out in the courtroom. 

Here's a case where jurors knew their rights during the *voir dire* process and prevented an unjust charge from ever going to trial: http://missoulian.com/news/local/article_464bdc0a-0b36-11e0-a594-001cc4c03286.html

**Comment by KacperZajc** [comment]
we could add 'the Jury's right to acquit shall not be obstructed' 
but I dont want to mention any 'bad' laws or 'unjust laws'  
and the question of law should still be determined by the judge

**Comment by FellowTraveler** [comment]
I changed the wording to: "The Jury shall have the right to rely on personal conscience to judge the merit of the law and its application, and shall be informed of this right."

**Comment by KacperZajc** [comment]
that would give them the official right to interpret the law
we can expressly guarantee the right to acquit in any event but for the sake of certainty the interpretation must be left to the judge

**Comment by FellowTraveler** [comment]
I changed the wording to: "The Jury has the right to rely on personal conscience to acquit any defendant as they see fit, and shall be informed of this right."

**Comment by KacperZajc** [comment]
then it is not a court of law, what is the difference between your proposal and random gathering of people to rule on another? 
all I can do is to put 'the right to acquit shall not be obstructed'

**Comment by FellowTraveler** [comment]
The judge is already qualified to render a verdict based on the law and the facts. If making a determination based on law is the only requirement, then we don't need any Jury at all. We can just have a judge with a hood over his face.

The reason we have Juries in the first place is because the people insisted on it, as a last line of defense against unjust laws being foisted upon them by a malicious king. The reason many marijuana prosecutions stopped happening in Montana is because they could never find a Jury willing to convict on a marijuana charge, even though it was "against the law." If those juries had ruled purely based on the facts, then they would have convicted. Why then have a Jury at all?

This one issue has resulted in so much injustice in the USA. Look at this article, "3 Examples of Jurors Regretting Guilty Verdicts" http://fija.org/2014/05/16/3-more-cases-of-juror-regrets-for-their-guilty-verdicts/ These things always happen because the jurors felt they had no choice based on the Judge's instructions.

This is not about a "random gathering of people ruling on another" as you say. They ARE supposed to find the defendant guilty if the facts show him to have broken the law. I do not dispute your point there. It should definitely be a court of law. But at the same time, the Jury needs the explicit right to acquit defendants who are innocent of wrongdoing, regardless of the law. This is the whole reason juries were invented in the first place.

And most importantly, the jury needs to be INFORMED of this right, because the history of injustice related to this issue has shown that most abuses happen due to judge's instructions.

===> The easiest way to get out of jury duty in the United States is to state that you believe in fully-informed juries who are educated on their right to nullify bad laws. The judge will drop you like a hot potato.

**Comment by KacperZajc** [comment]
the jury shall deliver the verdict of guilty or not guilty according to law it their determination on the culpability of defendant's mind

does this satisfy you?

**Comment by FellowTraveler** [comment]
How about: "**§VI.8.** The criminal offenses shall be tried in the Criminal Court before a panel of three judges with the panel of Jury to give a verdict of ‘Guilty’ or ‘Not guilty'; acquittal by Jury shall be final. The Jury shall render the verdict according to law and facts, and shall have the right to acquit based on personal conscience, and shall be informed of this right."

**Comment by KacperZajc** [comment]
"§VI.8. The criminal offences shall be tried in the Criminal Court before a panel of ONE JUDGE with the panel of Jury to give a verdict of ‘Guilty’ or ‘Not guilty'; the Jury shall render the verdict according to the law under advice of the judge, but shall determine the facts and the potential culpability of the defendant's mind retaining the right to acquit and shall be informed of this right; acquittal by Jury shall be final. 

???

**Comment by FellowTraveler** [comment]
> before a panel of ONE JUDGE

One judge is fine with me. The "three judges" part was already there (I didn't add it.)

> and the potential culpability of the defendant's mind

I'm not even sure what this means. Does a juror have a right of conscience or not?

Let's say you are on a Jury, and the crime is "possessing marijuana." And you want to acquit, because the law is unconstitutional, and because you think it is morally wrong to imprison someone for possessing marijuana. (This BTW is exactly the situation in the United States.) But the Judge instructs you that nevertheless, the actual legislation prohibits the possession of marijuana. And he instructs you that you MUST find the defendant guilty if the facts show that he possessed marijuana.

At this point, you feel really really bad, but you vote to convict, because you don't see that you had any other choice. This happens in the USA all the time, and it will happen in Liberland too (in a million different ways) if you don't explicitly give the jury the right to vote their conscience.

What's wrong with this wording? "§VI.8. The criminal offenses shall be tried in the Criminal Court before a panel of one judge with a panel of Jury to give a verdict of ‘Guilty’ or ‘Not guilty'; acquittal by Jury shall be final. The Jury shall render the verdict according to the law under advice of the judges, and shall determine the facts, but retains the right to acquit based on personal conscience, and shall be informed of this right."

**Comment by KacperZajc** [comment]
first of all if it is unconstitutional then you have to acquit

culpability is a state of mind whereby the defendant was either negligent or intended to do sth - so the judge says 'the law is ... and if you believe that the defendant intended to do so / was negligent you have to convict'

so they can think he did not intend or was not negligent and acquit, this is what I mean

**Comment by FellowTraveler** [comment]
> first of all if it is unconstitutional then you have to acquit

When the USA banned alcohol (Prohibition) it required a Constitutional Amendment. When Prohibition was repealed, it required another Constitutional Amendment.

Therefore the prohibition of intoxicants is unconstitutional in the USA and requires a Constitutional Amendment.

Yet Marijuana is illegal!! The legislation banning marijuana is thus unconstitutional. Should juries therefore acquit marijuana defendants? Yes they should. So why don't they? BECAUSE THE JUDGE INSTRUCTED THEM that if they find the facts show the defendant possessed marijuana, they must convict! Those juries feel really bad about convicting, and they are not aware of their right to vote their conscience.

> so they can think he did not intend or was not negligent and acquit, this is what I mean

So maybe he did not intend to possess marijuana. Maybe he didn't realize he possessed marijuana.

BUT -- what if he says, "YES I possessed that marijuana, and YES I smoked it, and I shouldn't have to go to prison for that, since I have done nothing wrong!"

Doesn't the jury in that case have a right to vote their conscience? The defendant deliberately broke the law, but he did nothing wrong.

This is not about intent.

**Comment by FellowTraveler** [comment]
Without jury nullification you might as well throw the rest of the Constitution in the toilet, since the judge will just instruct the jury to vote according to every abusive law that gets passed.

Jury nullification is the most important, the last line of defense, in a free society. Courts in the USA are notorious for misleading juries about this fundamental right, leading to all sorts of abuse of power.

Any Libertarian who lives in the USA will tell you, this is the most important one in the whole Constitution.

**Comment by joshmh** [comment]
I think there are two separate issues here. The right to vote your conscience and the right to uphold your interpretation of the constitution in the face of unconstitutional laws. I think we all agree that if you feel a law is unconstitutional you should acquit. This can be made more clear.

The right to vote your conscience is also clear, since you can't get in trouble for an acquital vote under any circumstances. The obligation of the judge to inform of this is where there's disagreement. I agree the judge should have to inform you of this, but I disagree that it's the most important right in the constitution, since I don't think it would be especially effective even if the judge made this clear every time.

In fact, I think the jury selection process is far more practically important.

**Comment by FellowTraveler** [comment]
There is no disagreement about the obligation to inform, since he actually added the inform part in his version.

**Comment by FellowTraveler** [comment]
Due to rebase issue, closing this PR and opening a new one.

**Comment by FellowTraveler** [comment]
The new PR is https://github.com/liberland/constitution/pull/72

**Comment by FellowTraveler** [comment]
The new PR is #344

**Pull request closed without merging**
