### PR TITLE
Add back self-defense

### PR DESCRIPTION
**Pull request by joshmh**
This was just removed, so I'm adding back in so we can discuss.

### CODE REVIEW

**Comment by KacperZajc** [comment]
this was removed on the personal request of President's assistant who is a criminologist and said it would be better to keep the right to bear arms separately from the right to self-defence which should be left to the jury.

**Comment by joshmh** [comment]
@KacperZajc I left the sections separated, but this lays out explicitly that there is a right to self defense and that one may defend himself with force against unlawful actions of agents of the state. I feel this is a cornerstone of the consensus we're trying to establish, and is certainly not self-evident based on my familiarity with the US and Israel. (Israel has a similar provision to what I added back, the US does not, except in a few states.)

**Comment by KacperZajc** [comment]
we can add this then:

The right to self-defense against initiators of aggression, including the agents of the Public Administration where acting unlawfully, is guaranteed

**Comment by KacperZajc** [comment]
oh sorry I havent noticed, yours is actually good :)

**Comment by joshmh** [comment]
:+1:

**Comment by KacperZajc** [comment]
add this Right but in the Individual Rights section of the Bill of Rights

**Pull request closed without merging**
