### PR TITLE
Every law requires a rationale

### PR DESCRIPTION
**Pull request by fare**
See issue #27.

### CODE REVIEW

**Comment by KacperZajc** [comment]
a bit too long plus add the requirement to read it aloud:

No Bill proposed to the Assembly shall be passed unless it has been read aloud by the Assembly Speaker and includes rationale and means of achieving thereof which does not conflict with the Constitution.

**Comment by fare** [comment]
I'd make the reading aloud a separate provision, and I would insist that no one may vote positively to introduce, amend or keep from expiring a law unless he has publicly read its entirety aloud during the legislature.

Note that all sponsors may read it aloud at the same time while the bill is being introduced for a discussion or vote, but that needs not be mentioned in the constitution itself.

**Comment by KacperZajc** [comment]
this provision is too long really, and I would combine those, there is no reason not to; here is what you want in a short form

No Bill proposed to the Assembly shall be passed unless it has been read aloud in entirety by the Assembly Speaker and includes rationale and means of achieving thereof which does not conflict with the Constitution.

**Comment by fare** [comment]
Actually I would include a budget restriction with every law, which plays well with nullification for bad cost/benefit analysis, and also plays well with sunsetting: the budget has to be renewed anyway. Linking the budget to individual laws also prevents the system of graft, opaqueness and log-rolling that appears when you vote budget as a single law.

That's a much better thing to put in the same article as the "must be read" provision, that is better to combine with sunsetting, since the two play together into limiting the overall size of the legislative code.

**Comment by KacperZajc** [comment]
we can add the requirement of budget but I dont agree with sun-setting as I wrote in various places 

No Bill proposed to the Assembly shall be passed unless it has been read aloud in entirety by the Assembly Speaker and includes precise calculation as to its potential impact on the budget as well as rationale behind it and means of achieving thereof, which does not conflict with the Constitution.

???

**Comment by KacperZajc** [comment]
we need stable laws, we need law that people now, we need to be predictable, how will you teach lawyers what the law is if it change change entirely every 4 years? not to mention that normal people dont have time to track all laws all the time because they all can change at once

i understand your intention guys but this is not the way to go

**Pull request closed without merging**
