### PR TITLE
Provision §II.4. Wording

### PR DESCRIPTION
**Pull request by yopdog**
>nothing in this provision shall prevent the collection of information which has been made available to the public or shared utterly voluntarily.

Changed to:
>nothing in this provision shall prevent the collection and sharing of information which has been made available to the public in any way or shared utterly voluntarily.

??

### CODE REVIEW

**Comment by terrorist96** [comment]
Facially, I'm not opposed to this change. However, I have to ask: what purpose do you hope to fulfil by making this change?

**Comment by yopdog** [comment]
'in any way' - makes it clear that regardless of how information becomes public it is free to use by anyone. 

'and sharing' - I think it's just better wording. makes it clear that you can use the information however you want. 

see #252

**Comment by terrorist96** [comment]
> 'in any way' - makes it clear that regardless of how information becomes public it is free to use by anyone.

There's no qualifiers listed for how it became public, so it covers any situation by default. 

> 'and sharing' - I think it's just better wording. Makes it clear that you can use the information however you want.

If you can collect it, sharing is moot. Sharing would only be disallowed for nonpublic information. 

Like I said, I'm not against these revisions, but I think the current language covers the situations you wish to protect.

**Comment by yopdog** [comment]
Yes, I see what you mean, but I still stand on this change. It makes it harder to interpret it differently. What you may see as the default by your logic, may not be what others see according to their interpretation.

**Comment by KacperZajc** [comment]
Im with @terrorist96 on that.

**Pull request closed without merging**
