### PR TITLE
Fixed conflicts

### PR DESCRIPTION
**Pull request by terrorist96**
I hate how sometimes it doesn't highlight the changes I make for some PRs. Do you know why this is?

### CODE REVIEW

**Comment by KacperZajc** [comment]
please list the changes in the comment :)

**Comment by terrorist96** [comment]
Fixed 'twenty' typo and added 'a' prior to Warrant and period.

**Comment by Jean-LouisMesic** [comment]
When in doubt, https://www.diffchecker.com/diff

**Comment by terrorist96** [comment]
Thanks! Bookmarked

**Comment by terrorist96** [comment]
Also apparently adding `.diff` to the end of any URL, you can see the difference more clearly

**Pull request merged**
