### PR TITLE
arms

### PR DESCRIPTION
**Pull request by terrorist96**
added light weapons, removed extra comma, removed `now`.

### CODE REVIEW

**Comment by KacperZajc** [comment]
per http://www.smallarmssurvey.org/weapons-and-markets/definitions.html :

small arms: revolvers and self-loading pistols, rifles and carbines, assault rifles, sub-machine guns and light machine guns.

light weapons: heavy machine guns, hand-held under-barrel and mounted grenade launchers, portable anti-aircraft guns, portable anti-tank guns, recoilless rifles, portable launchers of anti-tank missile and rocket systems; portable launchers of anti-aircraft missile systems (MANPADS); and mortars of calibres of less than 100 mm.

I think we should stick to small arms only.

**Comment by KacperZajc** [comment]
#294

**Comment by edwardtjgerety** [comment]
If you stick with Small Arms only you are voiding the Libertarian stance and now having government your babysitter. Telling you what is and not good for you.

**Comment by terrorist96** [comment]
In America, people are allowed to own cannons and flamethrowers. It doesn't seem like those would be included in small arms. (Maybe the flamethrower, but not cannons).

**Comment by TWalls** [comment]
Again, I think we are good with keeping the language at "small arms."
Personally I am a military collector, but do not have a problem with actual
destructive devices being subject to some kind of security clearance, since
one of the few roles of the state is to provide for and maintain security.

If I have an MP40 in my gun safe, and occasionally take it to the Liberland
gun range, that is no threat to anyone. However, if I mount a FLAK 88 on my
roof aimed straight at my neighbors' houses, they might rightfully view
that as a threat to their safety and object. The same might go for land
mines set up as booby traps in case someone accidentally trespasses on a
property. What about someone bringing in a tactical nuclear device? In
short I'm not in favor of "banning" anything, but with certain items,
certain considerations might be necessary. A lot of this becomes
theoretical quickly.

The U.S. National Firearms Act of 1934 - 26 U.S.C. § 5845 (F) defines and
regulates such items as "destructive devices." Ownership is regulated in a
similar manner to machine guns; ATF approval and tax stamps are required,
and in some cases, approval of the local chief law enforcement officer.
U.S. state laws may be even more restrictive on such items. I'm not saying
the U.S. system is ideal, and it is fraught with bureaucracy and
prosecutions for paperwork errors or omissions.  The Swiss also allow such
devices to be possessed with collectors with a special permit. The point is
there are other existing frameworks to look at and learn from while
maintaining our strong individual rights-cred.

We will also be subject to import/export regulations of the surrounding
countries as far as what may be brought in. That said, the former Yugoslav
Republics were and are major arms producers. The shooting sports are
particularly popular in Serbia and Prvi Partizan (Užice, Serbia) is a major
commercial ammunition manufacturer.

**Comment by terrorist96** [comment]
I removed light weapons for now. Please merge the other changes (removing `now` and an extra comma)

**Pull request merged**
