### PR TITLE
Making public Assembly and supreme Court challenges

### PR DESCRIPTION
**Pull request by terrorist96**

### CODE REVIEW

**Comment by KacperZajc** [comment]
§I.11. The affairs of the Assembly shall be video recorded and made public contemporaneously; any Assembly debate and votes or decision of any Court shall be recorded and archived and be made available to the general public.

There is no point video recording and transmitting contemporaneously court proceedings, no one watches those and it increases costs considering how many court proceedings we can expect.

**Comment by terrorist96** [comment]
On the contrary, I enjoy listening to the audio of some supreme court arguments in the USA. However, we don't have video of the proceedings. 

I'm ok with only having it applicable to the Supreme Court, but I don't know if we're going to have intermediate appeals courts. General District Courts should be exempt though - that would be ridiculous.

**Comment by KacperZajc** [comment]
§I.11. The affairs of the Assembly and the Supreme Court shall be video recorded and made public contemporaneously; any Assembly debate and votes or decision of any Court shall be recorded and archived and be made available to the general public.

???

**Comment by terrorist96** [comment]
Yea

**Comment by KacperZajc** [comment]
I added it to §I.7.

**Comment by terrorist96** [comment]
Can the 'be' prior to 'made' be omitted? Seems redundant.

**Comment by KacperZajc** [comment]
ok I'll fix it

**Pull request closed without merging**
