### PR TITLE
reasonable suspicion -> probable cause

### PR DESCRIPTION
**Pull request by terrorist96**

### CODE REVIEW

**Comment by KacperZajc** [comment]
see #441

**Comment by KacperZajc** [comment]
please update it as per #451 before I merge

**Comment by KacperZajc** [comment]
what's valid arrest?

**Comment by terrorist96** [comment]
I mentioned in the summary. 

> Added valid, so as to protect people for refusing to identify when it's not a valid (unconstitutional/unlawful) arrest.

**Pull request merged**
