### PR TITLE
Add purpose of government to the preamble.

### PR DESCRIPTION
**Pull request by JesseKPhillips**
This adds further introduction for why the Constitution exists.

### CODE REVIEW

**Comment by KacperZajc** [comment]
@JesseKPhillips your proposal revised + proposal to get rid of the 'law of nature' reference:

We, the Citizens of the Free Republic of Liberland, in order to secure Life, Liberty, and Property, for ourselves and future generations, do ordain and establish the Constitution of the Free Republic of Liberland, as its supreme law, deriving its just authority from the consent of the governed and nothing else. Being aware of a long and shameful list of governments’ trespasses to the Rights of the people, we hereby declare that the Public Authority governing the Free Republic of Liberland shall first and foremost respect the Bill of Rights and exercise only such functions as have been delegated to it under this Constitution. Therefore, drawing from the holy tradition of the Founding Fathers, we declare that whenever the Public Authority becomes an obstacle to, rather than a guarantor of, our Rights, it shall be our duty to alter or abolish such Government, and to institute a new Government for the restoration of the Rights which we consider inherent to all human beings.

**Comment by joshmh** [comment]
@KacperZajc I like this change, especially the acknowledgement of government trespasses and removal of natural law.

I've separated my main comment out for further discussion: https://github.com/liberland/constitution/issues/40

I have no problem with the clause about abolishing the government, but I'll point out that the New Hampshire constitution has an even gutsier article, which of course has had little effect on those in power or on judges in the court of law:

> [Art.] 10. [Right of Revolution.] Government being instituted for the common benefit, protection, and security, of the whole community, and not for the private interest or emolument of any one man, family, or class of men; therefore, whenever the ends of government are perverted, and public liberty manifestly endangered, and all other means of redress are ineffectual, the people may, and of right ought to reform the old, or establish a new government. **The doctrine of nonresistance against arbitrary power, and oppression, is absurd, slavish, and destructive of the good and happiness of mankind.**

**Comment by KacperZajc** [comment]
well yes that is more of a declaration than actual right but I think it sounds good :)

**Comment by JesseKPhillips** [comment]
@KacperZajc I'd suggest opening a new pull request in reference to the two issues you're combining; suggesting that the others be superseded.

I'm personally of the opinion that the Bill of Rights is poorly written, more so than the US Bill of Rights. Specifically the founders had it right utilizing the Bill of Rights as a secondary view, but not the primary; also the list of "No" being inappropriate. I'll be writing up an issue specifically for this section, but it is why I would not recommend the mention of the Bill of Rights in the preamble.

**Comment by KacperZajc** [comment]
I totally disagree with you, the Bill of Rights was very well received by both public and the President along with his colleagues. We dont want any major changes as to the Bill as a whole. And I believe it is a great idea to put it as a first to emphasises the point.

as to the new pull with changed preamble, feel free to create one, I am new to GitHub

**Comment by joshmh** [comment]
I'd like to point out that the founding fathers themselves bitterly debated the wisdom of the Bill of Rights. Even the father of the Bill of Rights, James Madison, [was skeptical](http://www.crisismagazine.com/1992/madisons-dilemma-and-ours-what-use-can-a-bill-of-rights-serve) of its utility:

> ... Madison thought a bill of rights was too weak a barrier to majority oppression, and why he thought it a matter of less than major importance. Efforts to restrain an oppressive majority were unlikely to succeed, **no matter what the solemn wording on parchment**. The best chance to protect rights lay in preventing the formation of an oppressive majority in the first place, and that is why **he considered the structure of the government and the society fundamental**, and the provisions of a bill of rights only secondary and supplemental.

**Comment by tinkyholloway** [comment]
I like this. What is the meaning of the word 'holy' in referring to the Founding Fathers? Who are the Founding Fathers in this context?

**Comment by KacperZajc** [comment]
Sentence "...it shall be our duty to alter or abolish such Government, and to institute a new Government for the restoration of the Rights which we consider inherent to all human beings" is very similar to the wording of the US Declaration of Independence so I mentioned the (US) Funding Fathers because it is their approach (tradition) this refers to. I called it holy to emphasise its significance, but this could be any other word.

**Comment by tinkyholloway** [comment]
I would prefer a different word to holy. Not my expertise, but maybe noble is better. Someone can do better than this. I don't like the religious connotations in a document founding a state that's all.

**Comment by joshmh** [comment]
One possibility:

> Therefore, drawing inspiration from the Declaration of Independence of the United States of America, we declare that whenever the Public Authority becomes an obstacle to, rather than a guarantor of, our Rights, it shall be our duty to alter or abolish such Government, and to institute a new Government for the restoration of the Rights which we consider inherent to all human beings.

**Comment by KacperZajc** [comment]
I really like the word 'noble'.
Id say '...drawing inspiration from the noble tradition of the Founding Fathers...'

**Comment by KacperZajc** [comment]
is everyone happy with this version?
or is 'Founding Fathers' vague? 

...Therefore, drawing inspiration from the noble tradition of the Founding Fathers, we declare that whenever the Public Authority becomes an obstacle to, rather than a guarantor of, our Rights, it shall be our duty to alter or abolish such Government, and to institute a new Government for the restoration of the Rights which we consider inherent in all human beings.

**Comment by KacperZajc** [comment]
I assume you all accept this wording?

**Comment by joshmh** [comment]
It's not clear that we're talking about the founding fathers of the US declaration of independence. I think you'd have to write:

> ...Therefore, drawing inspiration from the noble tradition of the drafters of the Declaration of Independence of the United States of America, we declare that whenever the Public Authority becomes an obstacle to, rather than a guarantor of, our Rights, it shall be our duty to alter or abolish such Government, and to institute a new Government for the restoration of the Rights which we consider inherent in all human beings.

**Comment by KacperZajc** [comment]
We, the Citizens of the Free Republic of Liberland, in order to secure Life, Liberty, and Property, for ourselves and future generations, do ordain and establish the Constitution of the Free Republic of Liberland, attempting a harmonious consensus for the benefit of all those seeking their home in this place. Being aware of a long and shameful list of governments’ trespasses to the Rights of the people, we hereby declare that the Public Authority governing the Free Republic of Liberland shall first and foremost respect the Bill of Rights and exercise only such functions as have been delegated to it under this Constitution. Therefore, drawing inspiration from the noble tradition of the drafters of the Founding Fathers of American Nation, we declare that whenever the Public Authority becomes an obstacle to, rather than a guarantor of, our Rights, it shall be our duty to alter or abolish such Government, and to institute a new Government for the restoration of the Rights which we consider inherent in all human beings.

can you get on board with that?
Id really like to mention 'Founding Fathers' rather than 'drafters'

**Comment by JesseKPhillips** [comment]
That one doesn't work at all. "Therefore, drawing inspiration from the noble tradition of the Founding Fathers of [the U.S.A.],"

Specifically, "drafters of the Founding Fathers" isn't proper and "American Nation" could be the North or South America with the former including Canada. The nation being reference has a formal name as "United States of America."

**Comment by KacperZajc** [comment]
sorry it was meant to be:

We, the Citizens of the Free Republic of Liberland, in order to secure Life, Liberty, and Property, for ourselves and future generations, do ordain and establish the Constitution of the Free Republic of Liberland, attempting a harmonious consensus for the benefit of all those seeking their home in this place. Being aware of a long and shameful list of governments’ trespasses to the Rights of the people, we hereby declare that the Public Authority governing the Free Republic of Liberland shall first and foremost respect the Bill of Rights and exercise only such functions as have been delegated to it under this Constitution. Therefore, drawing inspiration from the noble tradition of the Founding Fathers of American Nation, we declare that whenever the Public Authority becomes an obstacle to, rather than a guarantor of, our Rights, it shall be our duty to alter or abolish such Government, and to institute a new Government for the restoration of the Rights which we consider inherent in all human beings.

"United States of America" sounds to technical to me

**Comment by tinkyholloway** [comment]
Sorry for being so anal retentive: I would lower case Government. We have Public Administration as the proper noun. Otherwise I think it's a goer.

**Comment by KacperZajc** [comment]
you're right, 'g' it is :)

**Pull request closed without merging**
