### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by terrorist96**
Don't merge yet. I still need to go through most of the changes.

### CODE REVIEW

**Comment by terrorist96** [comment]
Ready to be merged.

**Comment by KacperZajc** [comment]
the problem with citizenship is that we dont want to give it away to anyone born to a citizen; it would be better to retain this as a prerogative; that's why I put automatic entitlement only where otherwise such a person would be stateless

**Comment by terrorist96** [comment]
That would require the Supreme Court to interpret the constitution and laws of every other country in the world in order to determine if someone is eligible for that citizenship.

**Comment by terrorist96** [comment]
@KacperZajc do you see my point?

**Comment by KacperZajc** [comment]
yes, that's a good point

how about:
"should a Person be born to parents of whom both are Citizens of the Free Republic of Liberland, he or she shall automatically be entitled to citizenship of the Free Republic of Liberland"

???

**Comment by terrorist96** [comment]
Ready to be merged. :)

**Pull request merged**
